### ISSUE TITLE
Como usar

### ISSUE THREAD

**Issue by zyxszzz** [ySnoopyDogy/Menhera-Tools#14]
como que usa isso?

**Comment by ySnoopyDogy** [comment]
Este projeto utiliza yarn. Instale todas as dependências com `yarn install`
Ele é um monorepo, então use cada comando de acordo com o repo que você quer usar (olhe os disponíveis no package do root)
dependendo do repositório tu vai precisar buildar, olha no package do projeto que tu quer usar se precisa ou não

Essa explicação tá bem por cima, se precisar de mais ajuda entre no servidor de [suporte da Menhera](https://discord.gg/fZMdQbA)
